# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# mostly from https://github.com/microsoft/torchgeo/blob/main/.github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "maintenance"
    groups:
      # torchvision pins torch, must update in unison
      torch:
        patterns:
          - "torch"
          - "torchvision"
    ignore:
      # setuptools releases new versions almost daily
      - dependency-name: "setuptools"
        update-types: ["version-update:semver-patch"]
      # segmentation-models-pytorch pins timm, must update in unison
      - dependency-name: "timm"
