ARG version
FROM python:$version-trixie

RUN echo "Preparing environment for Python $version"
RUN apt update
RUN apt install -y python3-pip bash 

RUN git clone https://github.com/terrastackai/terratorch.git
WORKDIR /terratorch
RUN pip install .[wxc,test,geobenchv2]


