ARG version
FROM python:$version-trixie

RUN echo "Preparing environment for Python $version"
RUN apt update
RUN apt install -y python3-pip bash 

COPY pyproject.toml .
COPY terratorch terratorch
COPY tests tests

RUN pip install --upgrade pip setuptools wheel
RUN pip install torch==2.4.0  # or whatever you need
RUN pip install -e .[wxc,test,geobenchv2]

CMD ["pytest", "-s", "--cov=terratorch", "-v", "--cov-report", "term-missing", "tests"]

