ARG version
FROM terratorch_python_$version:latest

RUN echo "Preparing environment for Python $version"

COPY pyproject.toml .
COPY terratorch terratorch
COPY tests tests

CMD ["pytest", "-s", "--cov=terratorch", "-v", "--cov-report", "term-missing", "tests"]
