# lightning.pytorch==2.1.1
seed_everything: 0
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 16-mixed
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: /opt/app-root/src/fm-geospatial/pf/logs/geobench-v2-substation
      name: dofa
  callbacks:
    # - class_path: RichProgressBar
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch
    # - class_path: ModelCheckpoint
    #   init_args:
    #       # dirpath: output/agb/checkpoints
    #       mode: max
    #       monitor: val_map
    #       filename: best-{epoch:02d}

  max_epochs: 100
  check_val_every_n_epoch: 1
  log_every_n_steps: 50
  enable_checkpointing: false
  default_root_dir: /opt/app-root/src/fm-geospatial/pf/logs/geobench-v2-substation
  
data:   
  class_path: GeoBenchV2ObjectDetectionDataModule
  init_args:
    cls: geobench_v2.datamodules.GeoBenchSubstationDataModule
  dict_kwargs:
    # batch_size: 8
    # eval_batch_size: 8
    num_workers: 32
    img_size: 224
    root: '/opt/app-root/src/fm-geospatial/data/GEO-Bench_V2'
    band_order: [B01, B02, B03, B04, B05, B06, B07, B08, B8A, B09, B10, B11, B12]
    collate_fn: geobench_v2.datamodules.substation.substation_collate_fn
    categories: [Background, Power Station]
    plot_indexes: [4,3,2]


model:
  class_path: terratorch.tasks.ObjectDetectionTask
  init_args:
    model_factory: ObjectDetectionModelFactory
    model_args:
      framework: mask-rcnn
      # backbone: dofav2_large_patch14_224
      # backbone_pretrained: true
      # backbone_ckpt_data: https://hf.co/earthflow/DOFA/resolve/main/dofav2_vit_large_e150.pth
      # backbone_pos_interpolation_mode: bicubic
      # backbone_convert_patch_14_to_16: True
      backbone: dofa_large_patch16_224
      backbone_pretrained: true
      backbone_pos_interpolation_mode: bicubic
      num_classes: 2
      backbone_img_size: 224
      framework_min_size: 224
      framework_max_size: 224
      backbone_model_bands: [COASTAL_AEROSOL, BLUE, GREEN, RED, RED_EDGE_1, RED_EDGE_2, RED_EDGE_3, NIR_BROAD, NIR_NARROW, WATER_VAPOR, CIRRUS, SWIR_1, SWIR_2]
      backbone_out_indices: [5, 11, 17, 23]
      necks:
        - name: ReshapeTokensToImage
        - name: LearnedInterpolateToPyramidal
        - name: FeaturePyramidNetworkNeck
        
    freeze_backbone: false
    freeze_decoder: false
    class_names: [Background, Power Station]
    
    boxes_field: 'bbox_xyxy'
    labels_field: 'label'
    masks_field: 'mask'
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1e-4
    weight_decay: 0.05

lr_scheduler:
  class_path: CosineAnnealingLR
  init_args:
    T_max: 20


