# lightning.pytorch==2.1.1
seed_everything: 42
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: bf16-mixed
  logger: true
  callbacks:
    - class_path: RichProgressBar
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: ModelCheckpoint
      init_args:
          dirpath: output/agb/checkpoints
          mode: min
          monitor: val/RMSE
          filename: best-{epoch:02d}
  max_epochs: 1
  log_every_n_steps: 5
  default_root_dir: output/agb/
  detect_anomaly: True

data:
  class_path: GenericNonGeoPixelwiseRegressionDataModule
  init_args:
    batch_size: 4
    num_workers: 2
    train_data_root: granite-geospatial-biomass-dataset/granite-geospatial-biomass-dataset/train_images/
    train_label_data_root: granite-geospatial-biomass-dataset/granite-geospatial-biomass-dataset/train_labels/
    val_data_root: granite-geospatial-biomass-dataset/granite-geospatial-biomass-dataset/val_images/
    val_label_data_root: granite-geospatial-biomass-dataset/granite-geospatial-biomass-dataset/val_labels/
    test_data_root: granite-geospatial-biomass-dataset/granite-geospatial-biomass-dataset/test_images/
    test_label_data_root: granite-geospatial-biomass-dataset/granite-geospatial-biomass-dataset/test_labels/
    img_grep: '*.tif'
    label_grep: '*.tif'
    means: 
      - 547.36707
      - 898.5121
      - 1020.9082
      - 2665.5352
      - 2340.584
      - 1610.1407
    stds:
      - 411.4701
      - 558.54065
      - 815.94025
      - 812.4403
      - 1113.7145
      - 1067.641
    train_transform:
      - class_path: albumentations.D4
      - class_path: ToTensorV2
    dataset_bands: [-1, BLUE, GREEN, RED, NIR_NARROW, SWIR_1, SWIR_2, -1, -1, -1, -1]
    output_bands: [BLUE, GREEN, RED, NIR_NARROW, SWIR_1, SWIR_2]
    rgb_indices:  [2, 1, 0]
    no_data_replace: 0
    no_label_replace: -1    

model:
  class_path: terratorch.tasks.PixelwiseRegressionTask
  init_args:
    model_factory: EncoderDecoderFactory
    model_args:
      backbone: prithvi_eo_v2_300
      backbone_pretrained: true
      backbone_num_frames: 1
      backbone_img_size: 512
      backbone_bands:
        - BLUE
        - GREEN
        - RED
        - NIR_NARROW
        - SWIR_1
        - SWIR_2
      necks:
        - name: SelectIndices
          indices: [5, 11, 17, 23]
        - name: ReshapeTokensToImage
        - name: LearnedInterpolateToPyramidal
      decoder: UNetDecoder
      decoder_channels: [512, 256, 128, 64]
    loss: rmse
    ignore_index: -1
    freeze_backbone: true
    freeze_decoder: false
    plot_on_val: true



optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1e-3
    weight_decay: 0.1
lr_scheduler:
  class_path: ReduceLROnPlateau
  init_args:
    monitor: val/loss
    factor: 0.5
    patience: 5

