# lightning.pytorch==2.1.1
seed_everything: 0
trainer:
  accelerator: auto
  strategy: auto
  devices: 1 # Number of GPUs, use 'auto' for local testing
  num_nodes: 1
  precision: 16-mixed
#  logger: True # will use default tensorboard logger
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: output/ForestNet
      name: timm_mae_vit  # Define experiment name
#    class_path: WandbLogger
#    init_args:
#      project: TerraTorch_ForestNet
#      name: timm_mae_vit
  callbacks:
    - class_path: RichProgressBar
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: EarlyStopping
      init_args:
        monitor: val/loss
        patience: 20

  max_epochs: 100
  check_val_every_n_epoch: 1
  log_every_n_steps: 50
  enable_checkpointing: true
  default_root_dir: output/ForestNet

data:
  class_path: terratorch.datamodules.GenericNonGeoClassificationDataModule
  init_args:
    batch_size: 16
    num_workers: 8
    dataset_bands: # Bands of your data
      - BLUE
      - GREEN
      - RED
      - NIR_NARROW
      - SWIR_1
      - SWIR_2
    output_bands: # Input bands of the model
      - BLUE
      - GREEN
      - RED
      - NIR_NARROW
      - SWIR_1
      - SWIR_2
    rgb_indices: # Indices of the RGB output bands
      - 2
      - 1
      - 0
    train_data_root: data/ForestNetDataset/train
    val_data_root: data/ForestNetDataset/val
    test_data_root: data/ForestNetDataset/test
    # constant_scale: 1  # Default case
    constant_scale: 39.216  # Scale 0-255 to 0-10000 (HLS data) (10000 / 255 = 39.216)
    means:
      - 775.229
      - 1080.992
      - 1228.585
      - 2497.202
      - 2204.213
      - 1610.832
    stds:
      - 1281.526
      - 1270.029
      - 1399.480
      - 1368.344
      - 1291.676
      - 1154.505
    num_classes: 12
    train_transform:
      - class_path: albumentations.RandomCrop
        init_args:
          height: 224
          width: 224
      - class_path: albumentations.HorizontalFlip
        init_args:
          p: 0.5
      - class_path: ToTensorV2
    val_transform:
      - class_path: albumentations.Resize
        init_args:
          height: 224
          width: 224
      - class_path: ToTensorV2
    test_transform:
      - class_path: albumentations.Resize
        init_args:
          height: 224
          width: 224
      - class_path: ToTensorV2

model:
  class_path: terratorch.tasks.ClassificationTask
  init_args:
    model_factory: TimmModelFactory
    model_args:
      backbone: vit_base_patch16_224.mae  # Name of the model
      pretrained: true
      in_channels: 6
      num_classes: 12
    freeze_backbone: false
    loss: ce
    class_names:  # Optional class names (Alphabetic order for generic classification dataset)
      - Fish pond
      - Grassland shrubland
      - Logging
      - Mining
      - Oil palm plantation
      - Other
      - Other large-scale plantations
      - Secondary forest
      - Small-scale agriculture
      - Small-scale mixed plantation
      - Small-scale oil palm plantation
      - Timber plantation

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1.e-4
    weight_decay: 0.05

lr_scheduler:
  class_path: CosineAnnealingLR
  init_args:
    T_max: 20
