# lightning.pytorch==2.1.1
seed_everything: 0
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 16-mixed
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: /opt/app-root/src/logs/
      name: od_resnet
  callbacks:
    # - class_path: RichProgressBar
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: ModelCheckpoint
      init_args:
          # dirpath: output/agb/checkpoints
          mode: max
          # monitor: val_map
          monitor: val_segm_map
          filename: best-{epoch:02d}
  max_epochs: 100
  check_val_every_n_epoch: 1
  log_every_n_steps: 50
  enable_checkpointing: true
  default_root_dir: /opt/app-root/src/logs/
  
data:
  class_path: terratorch.datamodules.mVHR10DataModule
  init_args:
    root: /opt/app-root/src/datasets/VHR10
    batch_size: 8
    num_workers: 8

model:
  class_path: terratorch.tasks.ObjectDetectionTask
  init_args:
    model_factory: ObjectDetectionModelFactory
    model_args:
      framework: mask-rcnn  # Model name of TorchVision (one of faster-rcnn, fcos, retinanet, mask-rcnn)
      backbone: timm_resnet50  
      backbone_pretrained: true
      framework_min_size: 896
      framework_max_size: 896 

      num_classes: 12  # Number of classes including background
      in_channels: 3
      necks:
        - name: FeaturePyramidNetworkNeck
        
    freeze_backbone: false
    freeze_decoder: false
    class_names:  # Optional class names (Alphabetic order for generic classification dataset)
      - Background
      - Airplane
      - Ships
      - Storage tank
      - Baseball diamond
      - Tennis court
      - Basketball court
      - Ground track field
      - Harbor
      - Bridge
      - Vehicle

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1e-4
    weight_decay: 0.05

lr_scheduler:
  class_path: CosineAnnealingLR
  init_args:
    T_max: 20


