defaults:
  terratorch_task:
    model_args:
      backbone: terramind_v1_tiny
      backbone_pretrained: true
    model_factory: ObjectDetectionModelFactory
    optimizer: AdamW
  trainer_args:
    log_every_n_steps: 1
    max_epochs: 50
experiment_name: od_aed_elephants_iterate
n_trials: 10
optimization_space:
  lr:
    log: true
    max: 1e-3
    min: 1e-6
    type: real
run_repetitions: 5
save_models: false
storage_uri: /dccstor/terratorch/users/rkie/iterate/logs/geobench/mlflow
tasks:
- datamodule:
    class_path: terratorch.datamodules.od_aed_elephant.ElephantDataModule
    init_args:
      img_folder_train: /dccstor/terratorch/shared/datasets/aed-elephant/AED/training_images                                                             
      ann_file_train: /dccstor/terratorch/shared/datasets/aed-elephant/annotations_elephants_training.json 
      img_folder_val: /dccstor/terratorch/shared/datasets/aed-elephant/AED/test_images
      ann_file_val: /dccstor/terratorch/shared/datasets/aed-elephant/annotations_elephants_test.json
      min_size: [3648, 5472]
      tile_size: [512, 512]
      overlap: 128
      batch_size: 8
      num_workers: 8
  direction: max
  metric: val_map
  name: elephants
  terratorch_task:
    model_factory: ObjectDetectionModelFactory
    model_args:
      framework: faster-rcnn
      backbone: terramind_v1_tiny
      backbone_pretrained: true
      num_classes: 2
      framework_min_size: 512
      framework_max_size: 512
      backbone_modalities:
      - RGB
      in_channels: 3
      necks:
      - name: SelectIndices
        indices:
        - 2
        - 5
        - 8
        - 11
      - name: ReshapeTokensToImage
        remove_cls_token: false
      - name: LearnedInterpolateToPyramidal
      - name: FeaturePyramidNetworkNeck
    freeze_backbone: false
    freeze_decoder: false
    class_names:  # Optional class names (Alphabetic order for generic classification dataset)
      - Background
      - Elephant
  type: object_detection