experiment_name: object_detection_aed_elephants_iterate
run_name: run1
defaults:
  trainer_args:
    accelerator: auto
    strategy: auto
    devices: auto
    num_nodes: 1
    precision: 16-mixed
    logger:
      class_path: TensorBoardLogger
      init_args:
        save_dir: .
        name: vit-large-timm_mask-rcnn
    callbacks:
      # - class_path: RichProgressBar
      - class_path: LearningRateMonitor
        init_args:
          logging_interval: epoch
      - class_path: ModelCheckpoint
        init_args:
            dirpath: output/elephants-base/checkpoints
            mode: max
            monitor: val_map
            filename: best-{epoch:02d}
            save_on_train_epoch_end: true
            every_n_epochs: 1
            save_top_k: 3
    max_epochs: 1000
    check_val_every_n_epoch: 10
    log_every_n_steps: 50
    enable_checkpointing: true
    default_root_dir: .
tasks:
  - name: od1
    type: objectdetection
    direction: max
    metric: val/Multiclass_Jaccard_Index
    early_stop_patience: 10
    terratorch_task:
      model_args:
        framework: faster-rcnn
        backbone: terramind_v1_tiny
        backbone_pretrained: true
        num_classes: 2
        framework_min_size: 512
        framework_max_size: 512
        backbone_modalities:
        - RGB
        in_channels: 3
        necks:
        - name: SelectIndices
          indices:
          - 2
          - 5
          - 8
          - 11
        - name: ReshapeTokensToImage
          remove_cls_token: false
        - name: LearnedInterpolateToPyramidal
        - name: FeaturePyramidNetworkNeck
      model_factory: ObjectDetectionModelFactory
      freeze_backbone: false
      freeze_decoder: false
      class_names:  # Optional class names (Alphabetic order for generic classification dataset)
        - Background
        - Elephant

    datamodule:
      class_path: terratorch.datamodules.od_aed_elephant.ElephantDataModule
      init_args:
        img_folder_train: /dccstor/terratorch/shared/datasets/aed-elephant/AED/training_images                                                             
        ann_file_train: /dccstor/terratorch/shared/datasets/aed-elephant/annotations_elephants_training.json 
        img_folder_val: /dccstor/terratorch/shared/datasets/aed-elephant/AED/test_images
        ann_file_val: /dccstor/terratorch/shared/datasets/aed-elephant/annotations_elephants_test.json
        min_size: [3648, 5472]
        tile_size: [512, 512]
        overlap: 128
        batch_size: 8
        num_workers: 8

n_trials: 4
save_models: False
storage_uri: /dccstor/terratorch/users/rkie/iterate/terratorch-iterate-test/
ray_storage_path: /dccstor/terratorch/users/rkie/iterate/terratorch-iterate-test/ray_storage
run_repetitions: 0
optimization_space:
  lr:
    max: 1e-3
    min: 1e-6
    type: real
    log: true
