benchmark_suffix: benchmark
experiment_name: benchmark
precision: 16-mixed
backbone: your_model_here

tasks:
  - name: cashew
    type: segmentation
    loss: ce
    bands:
      - RED
      - GREEN
      - BLUE
      - NIR_NARROW
    num_classes: 20
    max_epochs: 300
    direction: max
    datamodule:
      class_path: terratorch.datamodules.PASTISDataModule
      init_args:
        data_root: "/dccstor/geofm-finetuning/datasets/PASTIS/PASTIS-R"
        satellites:
          - "S2"
        target: "semantic"
        pad_image: 10
        truncate_image: 10
        batch_size: 16
        num_workers: 6
        val_transform:
          - class_path: FlattenTemporalIntoChannels
          - class_path: ToTensorV2
        train_transform:
          - class_path: FlattenTemporalIntoChannels
          - class_path: ToTensorV2
        test_transform:
          - class_path: FlattenTemporalIntoChannels
          - class_path: ToTensorV2
    decoder: UperNetDecoder
    decoder_args:
      channels: 128
      scale_modules: True
    metric: val/Multiclass_Jaccard_Index
    early_stop_patience: 50

n_trials: 16
save_models: False
storage_uri: /path/to/storage
ray_storage_path: /path/to/ray/storage
optimization_space:
  # decoder:
  #   - UperNetDecoder
  #   - UperNetDecoder
  lr:
    min: 1e-6
    max: 1e-3
    type: real
    log: true
  batch_size:
    - 4
    - 8
    - 16
    - 32
  decoder_channels:
    - 64
    - 128
    - 256
