# To use this config correctly for finetune
# terratorch fit --config /path/to/this/config --ckpt_path /path/to/checkpoint

seed_everything: 0
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 32
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: /your/dir
      name: chesapeake_finetune
  callbacks:
  - class_path: RichProgressBar
  - class_path: LearningRateMonitor
    init_args:
      logging_interval: epoch
  - class_path: ModelCheckpoint
    init_args:
      filename: best-{epoch:02d}-{val:.4f}
      monitor: val/Multiclass_Jaccard_Index
      save_top_k: 1
      mode: max
  - class_path: lightning.pytorch.callbacks.EarlyStopping
    init_args:
      monitor: val/Multiclass_Jaccard_Index
      patience: 50
      mode: max
  max_epochs: 100
  check_val_every_n_epoch: 1
  log_every_n_steps: 10
data:
  class_path: terratorch.datamodules.MChesapeakeLandcoverNonGeoDataModule
  init_args:
    partition: 1.00x_train
    train_transform:
      - class_path: albumentations.HorizontalFlip
        init_args:
          p: 0.5
      # - class_path: albumentations.RandomRotate90
      #   init_args:
      #     p: 0.5
      - class_path: albumentations.VerticalFlip
        init_args:
          p: 0.5
      # - class_path: albumentations.RandomBrightnessContrast
      #   init_args:
      #     p: 0.8
      - class_path: albumentations.Resize
        init_args:
          height: 224
          width: 224
      - class_path: ToTensorV2
    val_transform:
      - class_path: albumentations.Resize
        init_args:
          height: 224
          width: 224
      - class_path: ToTensorV2
    test_transform:
      - class_path: albumentations.Resize
        init_args:
          height: 224
          width: 224
      - class_path: ToTensorV2
    batch_size: 16
    num_workers: 6
    data_root: "/your/dataset/path"
    bands:
      - "RED"
      - "GREEN"
      - "BLUE"
      - "NIR"
model:
  class_path: terratorch.tasks.SemanticSegmentationTask
  init_args:
    model_factory: EncoderDecoderFactory
    model_args:
      backbone: prithvi_eo_tiny
      backbone_out_indices:
        - 2
        - 5
        - 8
        - 11
      decoder: UperNetDecoder
      decoder_channels: 128
      decoder_scale_modules: true
      backbone_bands:
      - RED
      - GREEN
      - BLUE
      - NIR_NARROW
      num_classes: 7
      rescale: true
      backbone_num_frames: 1
      backbone_embed_dim: 192
      backbone_depth: 12
      backbone_num_heads: 3
    loss: ce
    plot_on_val: true
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 9.466168325580654e-05
    weight_decay: 0.05676612087684485
