# lightning.pytorch==2.1.1
seed_everything: 0
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 16-mixed
  logger: True # will use tensorboardlogger
  callbacks:
    - class_path: RichProgressBar
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch

  max_epochs: 200
  check_val_every_n_epoch: 1
  log_every_n_steps: 50
  enable_checkpointing: true
  default_root_dir: <your_path_here>
data:
  class_path: terratorch.datamodules.GenericNonGeoSegmentationDataModule
  init_args:
    batch_size: 16
    num_workers: 8
    constant_scale: 0.0001
    dataset_bands:
      - COASTAL_AEROSOL
      - BLUE
      - GREEN
      - RED
      - RED_EDGE_1
      - RED_EDGE_2
      - RED_EDGE_3
      - NIR_BROAD
      - NIR_NARROW
      - WATER_VAPOR
      - CIRRUS
      - SWIR_1
      - SWIR_2
    output_bands:
      - BLUE
      - GREEN
      - RED
      - NIR_NARROW
      - SWIR_1
      - SWIR_2
    rgb_indices:
      - 2
      - 1
      - 0
    train_data_root: <sen1floods11_root>/v1.1/data/flood_events/HandLabeled/S2Hand/
    train_label_data_root: <sen1floods11_root>/v1.1/data/flood_events/HandLabeled/LabelHand
    val_data_root: <sen1floods11_root>/v1.1/data/flood_events/HandLabeled/S2Hand/
    val_label_data_root: <sen1floods11_root>/v1.1/data/flood_events/HandLabeled/LabelHand
    test_data_root: <sen1floods11_root>/v1.1/data/flood_events/HandLabeled/S2Hand/
    test_label_data_root: <sen1floods11_root>/v1.1/data/flood_events/HandLabeled/LabelHand
    # these must be obtained by running terratorch/examples/scripts/convert_sen1floods11_splits.py on the original split csv files
    train_split: <sen1floods11_root>/v1.1/splits/flood_handlabeled/flood_train_data.txt
    test_split: <sen1floods11_root>/v1.1/splits/flood_handlabeled/flood_test_data.txt
    val_split: <sen1floods11_root>/v1.1/splits/flood_handlabeled/flood_valid_data.txt
    img_grep: "*_S2Hand.tif"
    label_grep: "*_LabelHand.tif"
    no_label_replace: -1
    no_data_replace: 0
    means:
      - 0.1412956
      - 0.13795798
      - 0.12353792
      - 0.30902815
      - 0.2044958
      - 0.11912015
    stds:
      - 0.07406382
      - 0.07370365
      - 0.08692279
      - 0.11798815
      - 0.09772074
      - 0.07659938
    num_classes: 2

model:
  class_path: terratorch.tasks.SemanticSegmentationTask 
  init_args:
    model_factory: EncoderDecoderFactory
    model_args:
      backbone: prithvi_eo_v2_300
      backbone_pretrained: false
      backbone_ckpt_path: examples/Prithvi_EO_V2_300M.pt
      backbone_drop_path: 0.1
      backbone_bands:
        - BLUE
        - GREEN
        - RED
        - NIR_NARROW
        - SWIR_1
        - SWIR_2
      necks:
        - name: SelectIndices
#          indices: [2, 5, 8, 11] # 100M models
          indices: [5, 11, 17, 23] # 300M models
#          indices: [7, 15, 23, 31] # 600M models
        - name: ReshapeTokensToImage
        - name: LearnedInterpolateToPyramidal
      decoder: UNetDecoder
      decoder_channels: [512, 256, 128, 64]
      head_channel_list: [256]
      head_dropout: 0.1
      num_classes: 2
    loss: dice
    aux_heads:
      - name: aux_head
        decoder: FCNDecoder
        decoder_args:
          decoder_channels: 256
          decoder_in_index: -1
          decoder_num_convs: 2
          head_dropout: 0.1
    aux_loss:
      aux_head: 1.0
    ignore_index: -1
    freeze_backbone: false
    freeze_decoder: false

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1.e-4
    weight_decay: 0.1
lr_scheduler:
  class_path: ReduceLROnPlateau
  init_args:
    monitor: val/loss
    patience: 5
    factor: 0.5
